macro(ours_option NAME BRIEF ENABLE)
    option(CONFIG_${NAME} ${BRIEF} ${ENABLE}) 
    if (${ENABLE})
        add_definitions(-DOURS_CONFIG_${NAME}=1)
    else ()
        add_definitions(-DOURS_CONFIG_${NAME}=0)
    endif ()
endmacro(ours_option)

ours_option(KASLR "Enable/Disable kernel address space layout randomization" ON)
ours_option(ACPI "Enable/Disable ACPI" ON)
ours_option(NUMA "Enable/Disable NUMA support" ON)
ours_option(ZONE_DMA "Enable/Disable NUMA support" ON)
ours_option(ZONE_DMA32 "Enable/Disable NUMA support" ON)
ours_option(PLATFORM_PC "Enable PC platform support" ON)